// <auto-generated />
using System;
using HotelBookingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingApp.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20250909065034_add data 2")]
    partial class adddata2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("HotelBookingApp.Model.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOnBooking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBookingApp.Model.Domain.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDeluxRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDoubleRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSingleRooms")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            Name = "Glasgow Hotel",
                            NumberOfDeluxRooms = 2,
                            NumberOfDoubleRooms = 2,
                            NumberOfSingleRooms = 2
                        });
                });

            modelBuilder.Entity("HotelBookingApp.Model.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6528d02b-23de-4eba-8321-26321614394d"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 1,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = new Guid("959d8519-e10f-4c83-81a4-b4849878d51c"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 1,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = new Guid("bc4af3da-8e0b-49b1-9b00-8503ba54d4e1"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 2,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = new Guid("c2bc905b-b3ef-4c1f-a53d-68ec36c00840"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 2,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = new Guid("b30a4802-1e53-437c-9ec9-0e135769b0fa"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 3,
                            RoomType = "Deluxe"
                        },
                        new
                        {
                            Id = new Guid("f8d4b0ad-157a-4b7c-83b9-625a0c7f5e4b"),
                            HotelId = new Guid("727c5798-5771-43ca-9401-0ff3aed2d8c5"),
                            RoomCapacity = 3,
                            RoomType = "Deluxe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
